# Generated by Django 3.1 on 2021-03-14 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Желаемая должность')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Минимальная зарплата')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Максимальная зарплата')),
                ('currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='Валюта')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления резюме')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления резюме')),
                ('key_skills', models.TextField(blank=True, null=True, verbose_name='Ключевые навыки')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('opened', 'открыт')], default='opened', max_length=16, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128, verbose_name='Название компании')),
                ('job_title', models.CharField(max_length=128, verbose_name='Название вакансии')),
                ('from_date', models.DateField(verbose_name='Начало работы')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='Конец работы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experienceitems', to='jobseekerapp.resume')),
            ],
            options={
                'verbose_name': 'Место опыта для резюме',
                'verbose_name_plural': 'Места опыта для резюме',
            },
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_type', models.CharField(choices=[('high', 'высшее'), ('online', 'онлайн-курсы')], default='high', max_length=32, verbose_name='Тип образования')),
                ('degree', models.CharField(choices=[('master', 'магистр'), ('bachelor', 'бакалавр'), ('specialist', 'специлист'), ('sertificate', 'сертификат')], default='master', max_length=64, null=True, verbose_name='Уровень')),
                ('institution_name', models.CharField(max_length=64, verbose_name='Название учреждения')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='Начало периода')),
                ('to_date', models.DateField(verbose_name='Конец периода(фактическая или планируемая)')),
                ('course_name', models.CharField(max_length=256, verbose_name='Название курса/кафедры')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educationitems', to='jobseekerapp.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Место обучения для резюме',
                'verbose_name_plural': 'Места обучения для резюме',
            },
        ),
    ]
