# Generated by Django 3.1 on 2021-03-23 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0002_auto_20210314_1051'),
        ('jobseekerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата направления предложения')),
                ('cover_letter', models.TextField(blank=True, help_text='поле не обязательное', max_length=524, verbose_name='Сопроводительное письмо')),
                ('contact_phone', models.CharField(blank=True, help_text='поле не обязательное', max_length=12, verbose_name='Контактный телефон')),
                ('direction', models.CharField(max_length=1, verbose_name='Направление предложение (входящее/исходящее)')),
                ('status', models.CharField(choices=[('new', 'новое (не прочитано)'), ('read', 'прочитано'), ('approve', 'приглашение получено'), ('fail', 'отклонено')], default='new', max_length=16, verbose_name='Статус предложения')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseekerapp.resume', verbose_name='Резюме')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employerapp.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name_plural': 'Предложения по вакансиям от соискателей',
            },
        ),
    ]
