# Generated by Django 3.1 on 2021-03-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата направления отклика'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='direction',
            field=models.CharField(choices=[('O', 'исходящий'), ('I', 'входящий')], max_length=1, verbose_name='Направление отклика (входящее/исходящее)'),
        ),
    ]
