# Generated by Django 3.1 on 2021-03-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('employerapp', '0005_auto_20210325_2236'),
        ('jobseekerapp', '0003_auto_20210324_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления в избранное')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.jobseeker')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employerapp.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Избранная вакансия',
                'verbose_name_plural': 'Избранные вакансии',
            },
        ),
    ]
