# Generated by Django 3.1.1 on 2021-04-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0006_auto_20210331_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='failed_moderation',
            field=models.TextField(blank=True, max_length=254, verbose_name='Сообщение в случае непрохождения модерации резюме'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('draft', 'черновик'), ('opened', 'модерация пройдена успешно'), ('need_moderation', 'требуется модерация'), ('moderation_reject', 'модерация отклонена')], default='need_moderation', max_length=32, verbose_name='Статус'),
        ),
    ]
