# Generated by Django 3.1.1 on 2021-04-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0007_auto_20210412_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('draft', 'черновик'), ('opened', 'модерация пройдена успешно'), ('need_moderation', 'требуется модерация'), ('moderation_reject', 'модерация отклонена')], max_length=32, verbose_name='Статус'),
        ),
    ]
