# Generated by Django 3.1.1 on 2021-04-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20210412_1007'),
        ('jobseekerapp', '0008_auto_20210412_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.jobseeker'),
        ),
    ]
