# Generated by Django 3.1.1 on 2021-03-08 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('published', models.DateField(default=datetime.datetime.now, verbose_name='опубликовано')),
                ('description', models.TextField(verbose_name='текст новости')),
                ('is_active', models.BooleanField(default=True, verbose_name='новость активна')),
            ],
            options={
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
