# Generated by Django 3.1 on 2021-03-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descx', models.CharField(max_length=64, verbose_name='Описание типа отрасли')),
            ],
            options={
                'verbose_name_plural': 'Типы отраслей',
            },
        ),
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('middle_name', models.CharField(max_length=32, verbose_name='отчество')),
                ('gender', models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], max_length=16, verbose_name='пол')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('city', models.CharField(max_length=64, verbose_name='город')),
                ('married_status', models.CharField(choices=[('h', 'холост'), ('m', 'замужем/женат'), ('d', 'разведен/разведена')], max_length=1, verbose_name='Статус в браке')),
                ('photo', models.ImageField(blank=True, upload_to='jobseeker_photo')),
                ('phone_number', models.CharField(max_length=11, verbose_name='телефон')),
                ('about', models.TextField(blank=True, max_length=512, verbose_name='о себе')),
            ],
            options={
                'verbose_name_plural': 'Соискатели',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('company_name', models.CharField(max_length=256, unique=True, verbose_name='название компании')),
                ('tax_number', models.CharField(blank=True, max_length=16, verbose_name='ИНН компании')),
                ('phone_number', models.CharField(blank=True, max_length=11, verbose_name='телефон')),
                ('site', models.CharField(blank=True, max_length=32, verbose_name='сайт компании')),
                ('short_description', models.TextField(blank=True, verbose_name='краткое описание компании')),
                ('logo', models.ImageField(blank=True, upload_to='company_logo')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='город расположения компании')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('need_moderation', 'требуется модерация'), ('moderation_ok', 'модерация пройдена успешно'), ('moderation_reject', 'отклонено модератором')], default='draft', max_length=32, verbose_name='статус компании на сайте')),
                ('industry_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.industrytype')),
            ],
            options={
                'verbose_name_plural': 'Работодатели',
            },
        ),
    ]
