# Generated by Django 3.1.1 on 2021-04-08 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210407_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='failed_moderation',
            field=models.CharField(blank=True, max_length=512, verbose_name='поле заполняется в случае отклонения модерации'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='failed_moderation',
            field=models.CharField(blank=True, max_length=512, verbose_name='поле заполняется в случае отклонения модерации'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='status',
            field=models.CharField(choices=[('need_moderation', 'требуется модерация'), ('moderation_ok', 'модерация пройдена успешно'), ('moderation_reject', 'отклонено модератором')], default='need_moderation', max_length=32, verbose_name='статус компании на сайте'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 23, 55, 47, 174860)),
        ),
        migrations.AlterField(
            model_name='employer',
            name='status',
            field=models.CharField(choices=[('need_moderation', 'требуется модерация'), ('moderation_ok', 'модерация пройдена успешно'), ('moderation_reject', 'отклонено модератором')], default='need_moderation', max_length=32, verbose_name='статус компании на сайте'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 23, 55, 47, 181512)),
        ),
    ]
