# Generated by Django 3.1.1 on 2021-04-09 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210408_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 3, 7, 1, 824164)),
        ),
        migrations.AlterField(
            model_name='employer',
            name='status',
            field=models.CharField(choices=[('need_moderation', 'требуется модерация'), ('moderation_ok', 'модерация пройдена успешно'), ('moderation_reject', 'отклонено модератором'), ('draft', 'черновик')], default='need_moderation', max_length=32, verbose_name='статус компании на сайте'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 3, 7, 1, 830697)),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='status',
            field=models.CharField(choices=[('need_moderation', 'требуется модерация'), ('moderation_ok', 'модерация пройдена успешно'), ('moderation_reject', 'отклонено модератором'), ('draft', 'черновик')], default='need_moderation', max_length=32, verbose_name='статус компании на сайте'),
        ),
    ]
