# Generated by Django 3.1.1 on 2021-04-12 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210409_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 0, 40, 8, 336061)),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 0, 40, 8, 342588)),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='status',
            field=models.CharField(choices=[('need_moderation', 'требуется модерация'), ('moderation_ok', 'модерация пройдена успешно'), ('moderation_reject', 'отклонено модератором')], default='need_moderation', max_length=32, verbose_name='статус соискателя на сайте'),
        ),
    ]
