# Generated by Django 3.1.1 on 2021-04-12 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20210412_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 10, 7, 56, 819956)),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 10, 7, 56, 826523)),
        ),
    ]
