# Generated by Django 3.1.1 on 2021-03-20 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0001_initial'),
        ('employerapp', '0002_auto_20210314_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='дата направления предложения')),
                ('cover_letter', models.TextField(blank=True, help_text='поле не обязательное', max_length=524, verbose_name='Сопроводительное письмо по предлагаемой вакансии')),
                ('contact_phone', models.CharField(blank=True, help_text='поле не обязательное', max_length=12, verbose_name='конт. лицо с кем связываться по вакансии')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseekerapp.resume', verbose_name='предложение для резюме')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employerapp.vacancy', verbose_name='выберите вакансию по которой хотите направить предложение соискателю')),
            ],
            options={
                'verbose_name_plural': 'Предложения по работе для соискателей',
            },
        ),
    ]
