# Generated by Django 3.1 on 2021-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0004_auto_20210321_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendoffers',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='поле не обязательное', max_length=12, verbose_name='конт. тел с кем связываться по вакансии'),
        ),
    ]
