# Generated by Django 3.1 on 2021-03-31 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0005_auto_20210328_2331'),
        ('employerapp', '0005_auto_20210325_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteresumes', to='jobseekerapp.resume', verbose_name='избранное резюме'),
        ),
    ]
