# Generated by Django 3.1.1 on 2021-04-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0006_auto_20210331_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendoffers',
            name='status',
            field=models.CharField(choices=[('new', 'новое (не прочитано)'), ('read', 'прочитано')], default='new', max_length=32, verbose_name='статус предложения'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(blank=True, choices=[('руб.', 'руб.'), ('USD', 'USD'), ('EUR', 'EUR')], help_text='поле необязательное для заполнения', max_length=4, verbose_name='валюта'),
        ),
    ]
