# Generated by Django 3.1.1 on 2021-04-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0007_auto_20210407_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='action',
            field=models.CharField(choices=[('need_moderation', 'требуется модерация'), ('moderation_ok', 'модерация пройдена успешно'), ('moderation_reject', 'отклонено модератором')], max_length=64, verbose_name='статус вакансии'),
        ),
    ]
