# Generated by Django 3.1.1 on 2021-04-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0008_auto_20210408_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='action',
            field=models.CharField(choices=[('need_moderation', 'требуется модерация'), ('moderation_ok', 'модерация пройдена успешно'), ('moderation_reject', 'отклонено модератором'), ('draft', 'черновик')], max_length=64, verbose_name='статус вакансии'),
        ),
    ]
